'use client';

import { use, useEffect, useState } from 'react';
import Link from 'next/link';
import DashboardLayout from '../../../../components/DashboardLayout';
import { apiClient } from '../../../../services/apiClient';

const stages = ['Lead', 'Qualification', 'Proposal', 'Negotiation', 'Closed Won'];
const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', notation: 'compact', maximumFractionDigits: 1 }).format(value || 0);

export default function DealDetailPage({ params }) {
  const { id } = use(params); const [deal, setDeal] = useState(null); const [draft, setDraft] = useState(null); const [message, setMessage] = useState('');
  useEffect(() => { apiClient.getDealById(id).then(item => { setDeal(item); setDraft(item); }).catch(() => setDeal(false)); }, [id]);
  const save = async () => { const updated = await apiClient.updateDeal(id, draft); setDeal(updated); setDraft(updated); setMessage('Opportunity updated.'); };
  if (deal === null) return <DashboardLayout><div className="p-8 text-sm text-slate-500">Memuat opportunity…</div></DashboardLayout>;
  if (deal === false) return <DashboardLayout><div className="p-8 text-sm text-rose-600">Opportunity tidak ditemukan.</div></DashboardLayout>;
  return <DashboardLayout><section className="mx-auto max-w-4xl space-y-6"><Link href="/sales/pipeline" className="text-sm font-semibold text-blue-600">← Sales Pipeline</Link><div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">{deal.account}</h1><p className="mt-1 text-sm text-slate-500">{deal.id} · Owner: {deal.owner} · DATABASE</p></div>{message && <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<div className="grid gap-4 md:grid-cols-3"><article className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-400">Deal value</p><p className="mt-2 text-xl font-semibold">{money(deal.value)}</p></article><article className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-400">Weighted pipeline</p><p className="mt-2 text-xl font-semibold">{money(deal.expectedRevenue)}</p></article><article className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-400">Next action</p><p className="mt-2 text-sm font-semibold">{deal.nextAction || 'Not set'}</p></article></div><form onSubmit={event => { event.preventDefault(); save(); }} className="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Update opportunity</h2><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Stage<select value={draft.stage} onChange={event => setDraft({ ...draft, stage: event.target.value })} className="mt-1 w-full rounded-lg border p-2">{stages.map(stage => <option key={stage}>{stage}</option>)}</select></label><label className="text-sm">Next action<input value={draft.nextAction || ''} onChange={event => setDraft({ ...draft, nextAction: event.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Value<input type="number" value={draft.value} onChange={event => setDraft({ ...draft, value: Number(event.target.value) })} className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm">Probability<input type="number" min="0" max="1" step="0.05" value={draft.probability} onChange={event => setDraft({ ...draft, probability: Number(event.target.value) })} className="mt-1 w-full rounded-lg border p-2" /></label></div><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Save changes</button></form></section></DashboardLayout>;
}
