'use client';

import { useEffect, useMemo, useState } from 'react';
import DashboardLayout from '../../components/DashboardLayout';
import { useAuth } from '../../context/AuthContext';
import TaskCard from '../../components/TaskCard';
import { calculateTaskStatus } from '../../lib/taskUtils';
import { apiClient } from '../../services/apiClient';

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const weekdays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const taskDate = (task) => /^\d{4}-\d{2}-\d{2}$/.test(task.deadline || '') ? task.deadline : null;

function TaskCalendar({ tasks, cursor, selectedDate, onCursorChange, onSelectDate }) {
  const year = cursor.getFullYear(); const month = cursor.getMonth();
  const startOffset = (new Date(year, month, 1).getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate();
  const cells = Array.from({ length: Math.ceil((startOffset + days) / 7) * 7 }, (_, index) => index - startOffset + 1);
  const dateKey = (day) => `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  const countFor = (day) => tasks.filter(task => taskDate(task) === dateKey(day)).length;
  return <aside className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-900">Task Calendar</h2>{selectedDate && <button onClick={() => onSelectDate(null)} className="text-[11px] font-semibold text-blue-600">Clear filter</button>}</div><div className="mt-4 flex items-center justify-between"><button onClick={() => onCursorChange(new Date(year, month - 1, 1))} aria-label="Previous month" className="grid h-7 w-7 place-items-center rounded hover:bg-slate-100">‹</button><span className="text-xs font-semibold">{MONTHS[month]} {year}</span><button onClick={() => onCursorChange(new Date(year, month + 1, 1))} aria-label="Next month" className="grid h-7 w-7 place-items-center rounded hover:bg-slate-100">›</button></div><div className="mt-4 grid grid-cols-7 gap-1 text-center">{weekdays.map(day => <span key={day} className="py-1 text-[9px] font-semibold text-slate-400">{day}</span>)}{cells.map((day, index) => { const active = day > 0 && day <= days; const key = active ? dateKey(day) : null; const count = active ? countFor(day) : 0; const selected = key === selectedDate; return <button key={index} disabled={!active} onClick={() => onSelectDate(selected ? null : key)} className={`relative mx-auto grid h-8 w-8 place-items-center rounded-full text-[11px] transition ${!active ? 'text-slate-300' : selected ? 'bg-blue-600 font-semibold text-white' : count ? 'bg-blue-50 font-semibold text-blue-700 hover:bg-blue-100' : 'text-slate-700 hover:bg-slate-100'}`}>{active ? day : ''}{count > 0 && !selected && <i className="absolute bottom-0.5 h-1 w-1 rounded-full bg-blue-500" />}</button>; })}</div><p className="mt-4 border-t border-slate-100 pt-3 text-[11px] text-slate-500">Klik tanggal untuk menampilkan task yang jatuh tempo pada hari tersebut.</p></aside>;
}

export default function TaskBoardPage() {
  const { activeRole } = useAuth(); const [cursor, setCursor] = useState(new Date(2025, 4, 1)); const [selectedDate, setSelectedDate] = useState(null); const [tasks, setTasks] = useState();
  useEffect(() => { apiClient.fetchTasks().then(setTasks).catch(() => setTasks([])); }, []);
  const visibleTasks = useMemo(() => selectedDate ? (tasks || []).filter(task => taskDate(task) === selectedDate) : (tasks || []), [selectedDate, tasks]);
  const mockTasks = tasks || [];
  const columns = [
    { title: 'ON TRACK', label: 'Sesuai rencana', tasks: visibleTasks.filter(task => calculateTaskStatus(task.remaining_sla_hours, task.sla_hours) === 'ON TRACK'), dot: 'bg-emerald-500', border: 'border-emerald-100', action: 'border-emerald-200 text-emerald-700 hover:bg-emerald-50' },
    { title: 'AT RISK', label: 'Perlu perhatian', tasks: visibleTasks.filter(task => calculateTaskStatus(task.remaining_sla_hours, task.sla_hours) === 'AT RISK'), dot: 'bg-amber-500', border: 'border-amber-100', action: 'border-amber-200 text-amber-700 hover:bg-amber-50' },
    { title: 'OVERDUE', label: 'Melewati SLA', tasks: visibleTasks.filter(task => calculateTaskStatus(task.remaining_sla_hours, task.sla_hours) === 'OVERDUE'), dot: 'bg-rose-500', border: 'border-rose-100', action: 'border-rose-200 text-rose-700 hover:bg-rose-50' },
    { title: 'BLOCKED', label: 'Menunggu ketergantungan', tasks: visibleTasks.filter(task => task.dependencies?.some(dependency => dependency.status !== 'Resolved')), dot: 'bg-violet-500', border: 'border-violet-100', action: 'border-violet-200 text-violet-700 hover:bg-violet-50' }
  ];
  return <DashboardLayout><section className="mx-auto max-w-[1440px]"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Task Board</h1><p className="mt-1 text-sm text-slate-500">Pantau pekerjaan berdasarkan kondisi dan risiko SLA{selectedDate ? ` · Deadline ${selectedDate}` : ''}.</p></div><div className="flex flex-wrap gap-2"><button className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">Group by: Status</button><button onClick={() => { setCursor(new Date(2025, 4, 1)); setSelectedDate(null); }} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600">All tasks</button><span className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">{activeRole}</span></div></div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_290px]"><div className="grid min-h-[calc(100vh-180px)] grid-cols-1 gap-4 md:grid-cols-2 2xl:grid-cols-4">{columns.map(column => <section key={column.title} className={`flex min-h-80 flex-col rounded-xl border ${column.border} bg-white p-3 shadow-sm`}><div className="mb-3 flex items-start justify-between border-b border-slate-100 px-1 pb-3"><div><div className="flex items-center gap-2"><i className={`h-2 w-2 rounded-full ${column.dot}`} /><h2 className="text-xs font-semibold tracking-wide text-slate-800">{column.title}</h2></div><p className="mt-1 text-[11px] text-slate-500">{column.label}</p></div><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-600">{column.tasks.length}</span></div><div className="custom-scrollbar flex flex-1 flex-col gap-3 overflow-y-auto">{column.tasks.map(task => <TaskCard key={task.id} task={task} />)}{column.tasks.length === 0 && <p className="py-6 text-center text-xs text-slate-400">Tidak ada task pada tanggal ini</p>}</div><button className={`mt-3 rounded-lg border px-3 py-2 text-xs font-semibold transition ${column.action}`}>+ Add Task</button></section>)}</div><TaskCalendar tasks={mockTasks} cursor={cursor} selectedDate={selectedDate} onCursorChange={setCursor} onSelectDate={setSelectedDate} /></div></section></DashboardLayout>;
}
