import { mockTasks, mockCustomerSlas } from '../lib/mockData';
import { customers, decisionMatrixRules, employees, knowledgeItems, leadership, outcomes, pilots, projects, sectorBlueprints, servicePackages, workflowTemplates } from '../lib/operationalData';
import { calculateTaskStatus } from '../lib/taskUtils';

const delay = (value) => new Promise(resolve => setTimeout(() => resolve(value), 120));
const taskById = (id) => mockTasks.find(task => task.id === id);
const customerByName = (name) => customers.find(customer => customer.name === name);
const workload = (employee) => Math.round((employee.allocatedHours / employee.capacityHours) * 100);

function projectView(project) {
  const tasks = project.taskIds.map(taskById).filter(Boolean);
  const completed = tasks.filter(task => task.status === 'Resolved').length;
  return { ...project, customer: customers.find(c => c.id === project.customerId), package: servicePackages.find(p => p.id === project.packageId), workflows: project.workflowIds.map(id => workflowTemplates.find(w => w.id === id)), tasks, sla: mockCustomerSlas.find(s => s.id === project.slaId), progress: tasks.length ? Math.round((completed / tasks.length) * 100) : project.status === 'In progress' ? 50 : 0, outcome: outcomes.find(o => o.id === project.outcomeId), learnings: knowledgeItems.filter(item => project.learningIds.includes(item.id)) };
}

export const operationsService = {
  listCustomers: () => delay(customers.map(customer => ({ ...customer, projects: projects.filter(project => project.customerId === customer.id), slas: mockCustomerSlas.filter(sla => customer.slaIds.includes(sla.id)) }))),
  getCustomer: (id) => delay({ ...customers.find(customer => customer.id === id), projects: projects.filter(project => project.customerId === id).map(projectView), slas: mockCustomerSlas.filter(sla => customers.find(customer => customer.id === id)?.slaIds.includes(sla.id)) }),
  listProjects: () => delay(projects.map(projectView)),
  getProject: (id) => delay(projectView(projects.find(project => project.id === id))),
  listWorkflows: () => delay(workflowTemplates.map(workflow => ({ ...workflow, packages: servicePackages.filter(pkg => pkg.workflowIds.includes(workflow.id)), playbooks: knowledgeItems.filter(item => workflow.linkedPlaybookIds.includes(item.playbookId)) }))),
  listKnowledge: () => delay(knowledgeItems.map(item => ({ ...item, sourceProject: projects.find(project => project.id === item.sourceProjectId) }))),
  listPilots: () => delay(pilots.map(pilot => ({ ...pilot, customer: customers.find(c => c.id === pilot.customerId), workflow: workflowTemplates.find(w => w.id === pilot.workflowId), package: servicePackages.find(p => p.id === pilot.packageId) }))),
  listOutcomes: () => delay(outcomes.map(outcome => ({ ...outcome, customer: customers.find(c => c.id === outcome.customerId), project: projects.find(p => p.id === outcome.projectId) }))),
  getOrganization: () => delay({ leadership, employees, divisions: ['Teknologi', 'Implementasi', 'Support', 'Sales', 'Administrasi'].map(department => ({ department, manager: leadership.find(person => person.level === 'Manager' && person.department === department), employees: employees.filter(employee => employee.department === department) })) }),
  listBlueprints: () => delay(sectorBlueprints.map(blueprint => ({ ...blueprint, package: servicePackages.find(pkg => pkg.id === blueprint.packageId), workflows: blueprint.workflowIds.map(id => workflowTemplates.find(w => w.id === id)), playbooks: knowledgeItems.filter(item => blueprint.playbookIds.includes(item.playbookId)) }))),
  getTaskContext: (taskId) => { const task = taskById(taskId); const customer = customerByName(task?.customer); const project = projects.find(p => p.taskIds.includes(taskId)); return delay({ task, customer, project: project && projectView(project), workflow: project && workflowTemplates.find(w => w.id === project.workflowIds[0]), sla: mockCustomerSlas.find(s => s.id === task?.parent_customer_sla_id), dependencies: task?.dependencies?.map(dep => ({ ...dep, downstreamImpact: dep.status === 'Delayed' ? `${task.title} is blocked and its project SLA is at risk.` : 'No current downstream impact.' })) || [], knowledge: project ? knowledgeItems.filter(item => item.workflowId === project.workflowIds[0]) : [] }); },
  getCapacityRecommendations: (taskId) => { const task = taskById(taskId); return delay(employees.map(employee => ({ ...employee, workloadRatio: workload(employee), activeTasks: mockTasks.filter(t => t.owner?.initials === employee.initials), skillMatch: (task.required_skills || [task.department]).filter(skill => employee.skills.includes(skill)).length, suitable: employee.availability === 'Available' && workload(employee) < 90 })).sort((a, b) => Number(b.suitable) - Number(a.suitable) || b.skillMatch - a.skillMatch || a.workloadRatio - b.workloadRatio)); },
  getMonitoring: () => { const taskStates = mockTasks.map(task => ({ ...task, slaState: calculateTaskStatus(task.remaining_sla_hours, task.sla_hours), blocked: task.dependencies?.some(dep => dep.status !== 'Resolved') })); return delay({ projects: projects.map(projectView), workflows: workflowTemplates.map(workflow => ({ name: workflow.name, progress: projects.filter(p => p.workflowIds.includes(workflow.id)).length ? 50 : 0 })), capacity: employees.map(employee => ({ ...employee, workloadRatio: workload(employee) })), blockedTasks: taskStates.filter(task => task.blocked), bottlenecks: taskStates.filter(task => task.dependencies?.some(dep => dep.status === 'Delayed')), interventions: mockTasks.flatMap(task => task.intervention_history || []) }); },
  decide: ({ riskBand, slaState, dependencyDelayed, workloadRatio, priority, complexity }) => { let action = 'Monitor'; if (slaState === 'OVERDUE') action = 'Immediate Intervention'; else if (riskBand === 'High' && dependencyDelayed) action = 'Escalate Dependency'; else if (riskBand === 'High' && workloadRatio >= 90) action = 'Reassign Resource'; else if (riskBand === 'High' && priority === 'Low' && complexity >= 7) action = 'Adjust Priority'; return { action, advisory: true, reason: `Decision matrix: ${riskBand || 'Unknown'} risk, ${slaState}, dependency ${dependencyDelayed ? 'delayed' : 'clear'}, workload ${workloadRatio || 0}%.`, rules: decisionMatrixRules }; },
  confirmIntervention: ({ taskId, action, reason, actor = 'Budi Santoso', changes = {} }) => { const task = taskById(taskId); if (!task) return Promise.reject(new Error('Task not found')); const record = { id: `INT-${Date.now()}`, action, reason, actor, timestamp: new Date().toISOString(), source: 'Manager-confirmed' }; task.intervention_history = [record, ...(task.intervention_history || [])]; task.activity_history = [{ timestamp: record.timestamp, action: `Intervention: ${action}`, user: actor, reason }, ...(task.activity_history || [])]; Object.assign(task, changes); return delay({ task, record }); }
};
