'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import DashboardLayout from '../../components/DashboardLayout';
import { apiClient } from '../../services/apiClient';
import { calculateTaskStatus } from '../../lib/taskUtils';

const Kpi = ({ label, value, note, tone = 'text-slate-950' }) => <article className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-600">{label}</p><p className={`mt-3 text-2xl font-semibold tracking-tight ${tone}`}>{value}</p><p className="mt-1 text-[11px] text-slate-500">{note}</p></article>;

export default function EscalationsPage() {
  const [tasks, setTasks] = useState([]);
  const [search, setSearch] = useState('');
  useEffect(() => { apiClient.fetchTasks().then(setTasks).catch(() => setTasks([])); }, []);
  const records = useMemo(() => tasks.flatMap(task => (task.escalation_history || []).map((entry, index) => ({ ...entry, id: `ESC-${task.id}-${index}`, task }))).filter(item => `${item.task.title} ${item.reason || ''}`.toLowerCase().includes(search.toLowerCase())), [tasks, search]);
  const atRisk = tasks.filter(task => calculateTaskStatus(task.remaining_sla_hours, task.sla_hours) !== 'ON TRACK');
  const overdue = atRisk.filter(task => calculateTaskStatus(task.remaining_sla_hours, task.sla_hours) === 'OVERDUE');
  return <DashboardLayout><section className="mx-auto max-w-[1480px] space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Escalations</h1><p className="mt-1 text-sm text-slate-500">Monitor issues that need extra attention before the SLA is breached.</p></div><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search escalations…" className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs outline-none" /></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Escalation records" value={records.length} note="From persisted task history" /><Kpi label="Tasks at risk" value={atRisk.length} note="Need monitoring" tone="text-amber-600" /><Kpi label="Breaching SLA" value={overdue.length} note="Needs immediate action" tone="text-rose-600" /><Kpi label="On track" value={tasks.length - atRisk.length} note="Within SLA" tone="text-emerald-600" /><Kpi label="Tasks monitored" value={tasks.length} note="Live database data" /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-4"><article className="overflow-hidden rounded-xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-semibold">Escalation records</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th className="p-4">ID</th><th>Issue</th><th>Priority</th><th>Status</th><th>SLA</th><th>Owner</th></tr></thead><tbody className="divide-y divide-slate-100">{records.map(item => { const state = calculateTaskStatus(item.task.remaining_sla_hours, item.task.sla_hours); return <tr key={item.id}><td className="p-4 font-semibold text-blue-600">{item.id}</td><td><Link href={`/tasks/${item.task.id}`} className="font-semibold text-slate-800 hover:text-blue-600">{item.task.title}</Link><p className="mt-1 text-[10px] text-slate-500">{item.reason || item.action}</p></td><td>{item.task.task_priority}</td><td><span className={`rounded px-2 py-1 text-[10px] ${state === 'OVERDUE' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{state === 'OVERDUE' ? 'Breaching SLA' : 'Open'}</span></td><td>{item.task.remaining_sla_hours}h</td><td>{item.task.owner?.name}</td></tr>; })}{!records.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">No escalation records yet.</td></tr>}</tbody></table></div></article><article className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold">Escalation workflow</h2><div className="mt-4 grid gap-3 md:grid-cols-5">{['Identify', 'Triage', 'Assign', 'Resolve', 'Close'].map((step, index) => <div key={step} className="rounded-lg border border-slate-100 p-3"><span className="text-xs font-semibold text-blue-600">{index + 1}.</span><p className="mt-2 text-xs font-semibold">{step}</p></div>)}</div></article></div><aside className="space-y-4"><article className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold">SLA health</h2><div className="mt-4 space-y-3 text-xs"><p className="rounded-lg bg-rose-50 p-3 text-rose-700">Breaching SLA <b className="float-right">{overdue.length}</b></p><p className="rounded-lg bg-amber-50 p-3 text-amber-700">At risk <b className="float-right">{atRisk.length - overdue.length}</b></p><p className="rounded-lg bg-emerald-50 p-3 text-emerald-700">On track <b className="float-right">{tasks.length - atRisk.length}</b></p></div></article></aside></div>
  </section></DashboardLayout>;
}
