'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function LoginPage() {
  const [email, setEmail] = useState('arif.pratama@servenow.io'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const router = useRouter();
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); const response = await fetch('/api/auth/session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const body = await response.json(); setLoading(false); if (!response.ok) return setError(body.error); router.replace(body.user.role.startsWith('Direktur') ? '/overview' : body.user.role === 'Manager Sales' || body.user.role === 'Karyawan Sales' ? '/sales/pipeline' : body.user.role === 'Manager Administrasi' ? '/admin/users' : body.user.role.startsWith('Manager') ? '/team-dashboard' : '/my-work'); };
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-xl"><p className="text-sm font-semibold text-blue-600">ServeNow Workforce OS</p><h1 className="mt-2 text-2xl font-semibold text-slate-900">Masuk untuk demo</h1><p className="mt-2 text-sm text-slate-500">Masukkan email akun demo yang terdaftar. Tidak memerlukan password atau pengiriman email.</p><label className="mt-6 block text-sm font-medium text-slate-700">Email</label><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2" required /><p className="mt-2 text-xs text-slate-500">Contoh: arif.pratama@servenow.io atau fajar.ramadhan@servenow.io</p>{error && <p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading ? 'Memeriksa akun…' : 'Masuk'}</button></form></main>;
}
