'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import DashboardLayout from '../../components/DashboardLayout';
import { apiClient } from '../../services/apiClient';
import { statusLabel } from '../../lib/taskUtils';

const StatCard = ({ label, value, note, alert = false }) => <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><p className="text-sm font-semibold text-slate-800">{label}</p><p className="mt-5 text-3xl font-semibold tracking-tight text-slate-950">{value}</p><p className={`mt-3 text-xs font-medium ${alert ? 'text-rose-600' : 'text-emerald-600'}`}>{alert ? '●' : '▲'} {note}</p></article>;

function TrendChart() { return <svg viewBox="0 0 590 170" className="mt-5 h-48 w-full" role="img" aria-label="Tren pencapaian SLA"><g stroke="#e8edf5">{[34,76,118,160].map(y => <line key={y} x1="16" x2="572" y1={y} y2={y} />)}</g><path d="M16 139 C65 125 96 119 130 120 S196 109 240 111 S303 95 348 98 S413 84 468 87 S526 76 568 78" fill="none" stroke="#3b82f6" strokeWidth="3" /><path d="M16 122 C65 105 92 91 130 93 S197 74 240 76 S305 58 348 60 S415 42 468 46 S527 32 568 34" fill="none" stroke="#10b981" strokeWidth="3" />{[16,130,240,348,468,568].map((x,i) => <g key={x}><circle cx={x} cy={[122,93,76,60,46,34][i]} r="4.5" fill="#10b981" /><circle cx={x} cy={[139,120,111,98,87,78][i]} r="4.5" fill="#3b82f6" /><text x={x} y="166" textAnchor="middle" className="fill-slate-500 text-[11px]">{['19/05','20/05','21/05','23/05','24/05','25/05'][i]}</text></g>)}<text x="16" y="30" className="fill-slate-500 text-[11px]">100%</text><text x="16" y="72" className="fill-slate-500 text-[11px]">90%</text><text x="16" y="114" className="fill-slate-500 text-[11px]">80%</text></svg>; }

export default function OverviewPage() {
  const [data, setData] = useState(null);
  useEffect(() => { apiClient.getExecutiveOverviewData().then(setData); }, []);
  if (!data) return <DashboardLayout><div className="grid h-64 place-items-center text-sm text-slate-500">Memuat ringkasan perusahaan…</div></DashboardLayout>;
  const atRisk = data.weeklyExceptions; const overdue = data.criticalExceptions.filter(item => item.status === 'OVERDUE').length;
  const total = Math.max(1, data.deptSummary.reduce((sum, item) => sum + item.openTasks, 0)); const colors = ['#2563eb','#f59e0b','#8b5cf6','#06b6d4','#fb7185']; let offset = 0;
  const slices = data.deptSummary.map((item,index) => ({ ...item, color: colors[index], percent: Math.round(item.openTasks / total * 100) }));
  return <DashboardLayout><div className="mx-auto max-w-[1440px] space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><h1 className="text-3xl font-semibold tracking-tight text-slate-950">Executive Overview</h1><p className="mt-1 text-sm text-slate-500">Ringkasan kinerja perusahaan dalam satu tampilan.</p></div><div className="flex gap-2"><button className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 shadow-sm">Minggu ini⌄</button><button className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 shadow-sm">19 – 25 Mei 2025&nbsp; ◫</button></div></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="SLA Achievement" value={`${data.slaAchievement}%`} note="4.1% dibanding minggu lalu" /><StatCard label="At Risk Tasks" value={atRisk} note="12 tugas baru minggu ini" /><StatCard label="Overdue Tasks" value={overdue} note="Perlu ditangani segera" alert /><StatCard label="Pipeline Value" value={data.pipelineValue} note="11% dibanding minggu lalu" /></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-slate-100 bg-white p-6 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h2 className="text-lg font-semibold text-slate-900">SLA Achievement Trend</h2><p className="mt-1 text-xs text-slate-500">Perbandingan pencapaian SLA minggu ini dan minggu lalu.</p><TrendChart /><div className="flex justify-end gap-4 text-xs text-slate-600"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-500" />Minggu ini</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-blue-500" />Minggu lalu</span></div></article><article className="rounded-2xl border border-slate-100 bg-white p-6 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h2 className="text-lg font-semibold text-slate-900">At Risk by Department</h2><p className="mt-1 text-xs text-slate-500">Tugas berisiko yang perlu perhatian per tim.</p><div className="mt-6 flex flex-col items-center gap-7 sm:flex-row"><div className="relative"><svg viewBox="0 0 184 184" className="h-52 w-52 -rotate-90">{slices.map(item => { const result = <circle key={item.name} cx="92" cy="92" r="58" fill="none" stroke={item.color} strokeWidth="14" strokeDasharray={`${item.percent} ${100-item.percent}`} strokeDashoffset={-offset} pathLength="100" />; offset += item.percent; return result; })}</svg><div className="absolute inset-0 grid place-items-center text-center"><b className="text-3xl font-semibold">{atRisk}</b><span className="-mt-8 text-xs text-slate-500">Total</span></div></div><div className="w-full space-y-4">{slices.map(item => <div key={item.name} className="flex items-center justify-between gap-4 text-sm"><span className="flex items-center gap-2 text-slate-600"><i className="h-3 w-3 rounded-sm" style={{background:item.color}} />{item.name}</span><span className="font-medium text-slate-700">{item.openTasks} ({item.percent}%)</span></div>)}</div></div></article></section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-slate-100 bg-white p-6 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Critical Exceptions</h2><p className="mt-1 text-xs text-slate-500">Hal yang perlu keputusan atau tindakan segera.</p></div><Link href="/interventions" className="text-sm font-semibold text-blue-600">View all</Link></div><div className="mt-5 divide-y divide-slate-100">{data.criticalExceptions.map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-4"><div className="flex min-w-0 items-start gap-3"><span className={`mt-1 h-3 w-3 rounded-full ${item.status === 'OVERDUE' ? 'bg-rose-500' : 'bg-amber-400'}`} /><div><Link href={`/tasks/${item.id}`} className="text-sm font-semibold text-slate-800 hover:text-blue-600">{item.title}</Link><p className="mt-1 text-xs text-slate-500">{item.customer} · {item.owner}</p></div></div><span className={`rounded-md px-3 py-1 text-[10px] font-semibold ${item.status === 'OVERDUE' ? 'bg-rose-50 text-rose-600' : 'bg-amber-50 text-amber-700'}`}>{statusLabel(item.status)}</span></div>)}</div></article><article className="rounded-2xl border border-slate-100 bg-white p-6 shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h2 className="text-lg font-semibold text-slate-900">Director Dependency Indicator</h2><p className="mt-1 text-xs text-slate-500">Seberapa sering kegiatan operasional masih perlu keterlibatan direksi.</p><div className="mx-auto mt-8 grid h-52 w-72 place-items-center rounded-t-full border-[14px] border-emerald-600 border-b-0"><div className="text-center"><p className="text-4xl font-semibold text-slate-950">{data.directorDependency}</p><p className="mt-1 text-xs text-slate-500">Total</p><p className="mt-5 text-xs font-medium text-emerald-600">▼ 7% dibanding 30 hari lalu</p></div></div><p className="mt-4 text-center text-sm text-slate-600">Arah yang baik. Terus kurangi ketergantungan pada direksi.</p></article></section>
  </div></DashboardLayout>;
}
