'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { mockTasks } from '../../lib/mockData';
import { calculateTaskStatus } from '../../lib/taskUtils';
import { employees } from '../../lib/operationalData';
import { operationsService } from '../../services/operationsService';

const Loading = () => <div className="flex h-48 items-center justify-center text-sm text-slate-500">Loading operational data…</div>;
const Pill = ({ children, tone = 'slate' }) => <span className={`rounded border px-2 py-0.5 text-[10px] font-bold ${tone === 'rose' ? 'border-rose-100 bg-rose-50 text-rose-700' : tone === 'amber' ? 'border-amber-100 bg-amber-50 text-amber-700' : tone === 'emerald' ? 'border-emerald-100 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-slate-50 text-slate-600'}`}>{children}</span>;

export function OrganizationView() { const [monitoring, setMonitoring] = useState(); useEffect(() => { operationsService.getMonitoring().then(setMonitoring); }, []); if (!monitoring) return <Loading />; return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Organization & Capacity</h1><p className="text-sm text-slate-500">People, skills, workload and active operational coverage. <b>MOCK / DERIVED</b></p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{monitoring.capacity.map(employee => <article key={employee.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{employee.name}</h2><p className="text-xs text-slate-500">{employee.department} · {employee.experienceYears} yrs</p></div><Pill tone={employee.workloadRatio >= 90 ? 'rose' : 'emerald'}>{employee.workloadRatio}% load</Pill></div><p className="mt-4 text-xs text-slate-600">Skills: {employee.skills.join(', ')}</p><p className="mt-2 text-xs text-slate-500">Availability: {employee.availability} · {employee.allocatedHours}/{employee.capacityHours}h allocated</p></article>)}</div></section>; }

export function WorkloadView() { const [monitoring, setMonitoring] = useState(); useEffect(() => { operationsService.getMonitoring().then(setMonitoring); }, []); if (!monitoring) return <Loading />; return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Workload & Allocation</h1><p className="text-sm text-slate-500">Capacity visibility supports manager decisions; it never reassigns automatically. <b>DERIVED</b></p></div><div className="rounded-xl border bg-white shadow-sm"><div className="grid grid-cols-[1.2fr_2fr_100px] gap-4 border-b p-4 text-[10px] font-bold uppercase tracking-wider text-slate-400"><span>Employee</span><span>Capacity</span><span>State</span></div>{monitoring.capacity.map(employee => <div key={employee.id} className="grid grid-cols-[1.2fr_2fr_100px] items-center gap-4 border-b p-4 last:border-0"><div><b className="text-sm">{employee.name}</b><p className="text-xs text-slate-500">{employee.skills.join(', ')}</p></div><div><div className="h-2 rounded bg-slate-100"><div className={`h-2 rounded ${employee.workloadRatio >= 90 ? 'bg-rose-500' : employee.workloadRatio >= 75 ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${employee.workloadRatio}%` }} /></div><p className="mt-1 text-xs text-slate-500">{employee.allocatedHours}/{employee.capacityHours} hours · {employee.workloadRatio}%</p></div><Pill tone={employee.workloadRatio >= 90 ? 'rose' : employee.workloadRatio >= 75 ? 'amber' : 'emerald'}>{employee.availability}</Pill></div>)}</div><Link href="/team-dashboard" className="inline-block text-sm font-semibold text-indigo-600">Open manager monitoring →</Link></section>; }

export function RootCauseView() { const [items, setItems] = useState(); useEffect(() => { Promise.all([operationsService.getMonitoring(), operationsService.listProjects()]).then(([monitoring, projects]) => setItems({ monitoring, projects })); }, []); if (!items) return <Loading />; const exceptions = [...items.monitoring.bottlenecks, ...items.monitoring.blockedTasks.filter(task => !items.monitoring.bottlenecks.some(item => item.id === task.id))]; return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Root Cause Explorer</h1><p className="text-sm text-slate-500">Derived operational causes complement model-generated SHAP explanations on each task.</p></div>{exceptions.map(task => { const delayed = task.dependencies?.find(dep => dep.status === 'Delayed'); const cause = delayed ? 'Dependency Delay' : task.task_queue_age_hours > 12 ? 'Queue Age' : 'Workload Pressure'; return <article key={task.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><Link href={`/tasks/${task.id}`} className="font-semibold text-indigo-600">{task.title}</Link><p className="mt-1 text-xs text-slate-500">{task.customer} · {task.owner?.name} · {calculateTaskStatus(task.remaining_sla_hours, task.sla_hours)}</p></div><Pill tone="rose">{cause}</Pill></div><p className="mt-4 text-sm text-slate-600">{delayed ? `${delayed.task_id} is delayed under ${delayed.owner}; this blocks downstream task delivery.` : 'Review queue pressure and owner allocation before SLA buffer expires.'}</p><Link href={`/tasks/${task.id}`} className="mt-3 inline-block text-xs font-bold text-indigo-600">Open task, model analysis & decision →</Link></article>})}{!exceptions.length && <p className="rounded-xl border bg-white p-6 text-sm text-slate-500">No active dependency bottlenecks.</p>}</section>; }

export function InterventionView() { const [tasks, setTasks] = useState(mockTasks); const [selected, setSelected] = useState(null); const [action, setAction] = useState('Review / Coach'); const [reason, setReason] = useState('Manager reviewed task context.'); const [message, setMessage] = useState(''); const open = tasks.filter(task => task.status !== 'Resolved'); const submit = async () => { if (!selected || !reason.trim()) return; await operationsService.confirmIntervention({ taskId: selected.id, action, reason }); setMessage(`Intervention recorded for ${selected.id}.`); setSelected(null); setReason('Manager reviewed task context.'); }; return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Manager Interventions</h1><p className="text-sm text-slate-500">Every action needs confirmation, a reason, actor and timestamp. <b>MOCK PERSISTENCE</b></p></div>{message && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}<div className="grid gap-4 lg:grid-cols-2">{open.map(task => <article key={task.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><Link className="font-semibold text-indigo-600" href={`/tasks/${task.id}`}>{task.title}</Link><p className="mt-1 text-xs text-slate-500">{task.owner?.name} · {task.customer}</p></div><Pill tone={calculateTaskStatus(task.remaining_sla_hours, task.sla_hours) === 'OVERDUE' ? 'rose' : 'amber'}>{calculateTaskStatus(task.remaining_sla_hours, task.sla_hours)}</Pill></div><button onClick={() => setSelected(task)} className="mt-4 rounded bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Record decision</button></article>)}</div>{selected && <div className="rounded-xl border border-indigo-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Confirm intervention: {selected.title}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select value={action} onChange={event => setAction(event.target.value)} className="rounded border p-2 text-sm">{['Reassign Resource', 'Escalate Dependency', 'Adjust Priority', 'Review / Coach', 'No Action'].map(option => <option key={option}>{option}</option>)}</select><input value={reason} onChange={event => setReason(event.target.value)} className="rounded border p-2 text-sm" aria-label="Intervention reason" /></div><div className="mt-4 flex gap-2"><button onClick={submit} className="rounded bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Confirm & log</button><button onClick={() => setSelected(null)} className="rounded border px-3 py-2 text-xs font-bold">Cancel</button></div></div>}</section>; }

export function EscalationView() { const [monitoring, setMonitoring] = useState(); useEffect(() => { operationsService.getMonitoring().then(setMonitoring); }, []); if (!monitoring) return <Loading />; const history = mockTasks.flatMap(task => (task.escalation_history || []).map(item => ({ ...item, task }))).sort((a,b) => new Date(b.timestamp) - new Date(a.timestamp)); return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Escalations</h1><p className="text-sm text-slate-500">Escalated dependency and SLA events with direct links to the work item. <b>MOCK / DERIVED</b></p></div><div className="rounded-xl border bg-white shadow-sm">{history.map((entry, index) => <article key={`${entry.task.id}-${index}`} className="border-b p-5 last:border-0"><div className="flex justify-between gap-4"><div><Link href={`/tasks/${entry.task.id}`} className="font-semibold text-indigo-600">{entry.task.title}</Link><p className="mt-1 text-sm text-slate-700">{entry.action}</p><p className="mt-1 text-xs text-slate-500">{entry.reason} · {entry.user}</p></div><Pill tone="rose">{new Date(entry.timestamp).toLocaleString('en-GB')}</Pill></div></article>)}{!history.length && <p className="p-6 text-sm text-slate-500">No escalations recorded.</p>}</div></section>; }
