'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { operationsService } from '../../services/operationsService';

const Source = ({ children = 'MOCK' }) => <span className="text-[9px] font-bold tracking-wider text-slate-400">{children}</span>;
const Loading = () => <div className="p-8 text-sm text-slate-500">Memuat data operasional…</div>;

export function CustomerList() { const [items, setItems] = useState(); useEffect(() => { operationsService.listCustomers().then(setItems); }, []); if (!items) return <Loading />; return <section className="space-y-4"><div><h1 className="text-2xl font-bold">Pelanggan</h1><p className="text-sm text-slate-500">Janji kepada pelanggan terhubung ke proyek, alur kerja, tugas, dan hasilnya. <Source /></p></div><div className="grid gap-4 md:grid-cols-2">{items.map(item => <Link key={item.id} href={`/customers/${item.id}`} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm hover:border-indigo-300"><div className="flex justify-between"><b>{item.name}</b><span className="text-xs text-slate-500">{item.tier}</span></div><p className="mt-2 text-sm text-slate-500">{item.sector} · {item.contract}</p><p className="mt-3 text-xs font-medium text-indigo-600">{item.projects.length} proyek · {item.slas.length} SLA</p></Link>)}</div></section>; }

export function CustomerDetail({ id }) { const [item, setItem] = useState(); useEffect(() => { operationsService.getCustomer(id).then(setItem); }, [id]); if (!item) return <Loading />; return <section className="space-y-5"><Link href="/customers" className="text-sm text-indigo-600">← Customers</Link><div><h1 className="text-2xl font-bold">{item.name}</h1><p className="text-sm text-slate-500">{item.contract} · {item.sector} · <Source /></p></div><div className="grid gap-4 md:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Customer SLA commitments</h2>{item.slas.map(sla => <div key={sla.id} className="mt-3 border-t pt-3"><b className="text-sm">{sla.title}</b><p className="text-xs text-slate-500">{sla.status} · {sla.remaining_sla_hours}h remaining</p></div>)}</article><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Projects</h2>{item.projects.map(project => <Link key={project.id} href={`/projects/${project.id}`} className="mt-3 block border-t pt-3 text-sm text-indigo-600">{project.name} <span className="text-slate-500">— {project.status}</span></Link>)}</article></div></section>; }

export function ProjectList() {
  const [items, setItems] = useState(); const [customers, setCustomers] = useState(); const [packages, setPackages] = useState(); const [form, setForm] = useState({ customerId: '', packageId: '', name: '', scope: '' }); const [formOpen, setFormOpen] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const refresh = () => operationsService.listProjects().then(setItems).catch(error => { setError(error.message); setItems([]); });
  useEffect(() => { refresh(); Promise.all([operationsService.listCustomers(), operationsService.listServicePackages()]).then(([customerData, packageData]) => { setCustomers(customerData); setPackages(packageData); }); }, []);
  const submit = async (event) => { event.preventDefault(); if (!form.customerId || !form.packageId) return; setError(''); try { const project = await operationsService.createProject(form); setMessage(`${project.name}: alur kerja, titik pemeriksaan, pemilik tugas, SLA, dan ketergantungan sudah siap.`); setForm({ customerId: '', packageId: '', name: '', scope: '' }); setFormOpen(false); refresh(); } catch (error) { setError(error.message); } };
  if (!items || !customers || !packages) return <Loading />;
  return <section className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Proyek</h1><p className="text-sm text-slate-500">Mulai proyek dari paket pelanggan; sistem membuat alur kerja, titik pemeriksaan, pemilik tugas, dan rangkaian SLA. <Source>DATABASE</Source></p></div><button onClick={() => setFormOpen(value => !value)} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white">{formOpen ? 'Batal' : 'Buat proyek dari paket'}</button></div>{error && <p className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{formOpen && <form onSubmit={submit} className="grid gap-3 rounded-xl border border-indigo-100 bg-indigo-50/40 p-4 md:grid-cols-2"><select required value={form.customerId} onChange={event => setForm({ ...form, customerId: event.target.value })} className="rounded-lg border bg-white p-2 text-sm"><option value="">Pilih pelanggan</option>{customers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={form.packageId} onChange={event => setForm({ ...form, packageId: event.target.value })} className="rounded-lg border bg-white p-2 text-sm"><option value="">Pilih paket layanan</option>{packages.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="rounded-lg border bg-white p-2 text-sm" placeholder="Nama proyek (opsional)" /><input value={form.scope} onChange={event => setForm({ ...form, scope: event.target.value })} className="rounded-lg border bg-white p-2 text-sm" placeholder="Ruang lingkup (opsional)" /><button className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white md:col-span-2">Buat pekerjaan operasional</button></form>}{message && <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{items.map(item => <Link key={item.id} href={`/projects/${item.id}`} className="block rounded-xl border bg-white p-5 shadow-sm hover:border-indigo-300"><div className="flex justify-between gap-4"><div><b>{item.name}</b><p className="mt-1 text-sm text-slate-500">{item.customer.name} · {item.package.name} · {item.tasks.length} tugas</p></div><span className="text-sm font-semibold text-indigo-700">{item.progress}%</span></div><div className="mt-3 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-indigo-500" style={{ width: `${item.progress}%` }} /></div></Link>)}</section>;
}

export function ProjectDetail({ id }) { const [item, setItem] = useState(); useEffect(() => { operationsService.getProject(id).then(setItem); }, [id]); if (!item) return <Loading />; return <section className="space-y-5"><Link href="/projects" className="text-sm text-indigo-600">← Projects</Link><div><h1 className="text-2xl font-bold">{item.name}</h1><p className="text-sm text-slate-500">{item.scope} · <Source>POSTGRESQL</Source></p></div><div className="grid gap-4 md:grid-cols-3"><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Workflow</h2>{item.workflows.map(workflow => <p key={workflow.id} className="mt-2 text-sm">{workflow.name}</p>)}</article><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Milestones</h2>{item.milestones.map(m => <p key={m.name} className="mt-2 text-sm">{m.name}: <span className="text-slate-500">{m.status}</span></p>)}</article><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Outcome</h2><p className="mt-2 text-sm text-slate-600">{item.outcome ? item.outcome.resolutionStatus : 'In progress — outcome pending'}</p></article></div><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Operational tasks</h2>{item.tasks.map(task => <Link key={task.id} href={`/tasks/${task.id}`} className="mt-3 block border-t pt-3 text-sm text-indigo-600">{task.title} <span className="text-slate-500">— {task.owner?.name}</span></Link>)}</article><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Learning and playbooks</h2>{item.learnings.map(learning => <p key={learning.id} className="mt-2 text-sm">{learning.title} <span className="text-slate-500">({learning.status})</span></p>)}</article></section>; }

export function WorkflowLibrary() { const [items, setItems] = useState(); useEffect(() => { operationsService.listWorkflows().then(setItems); }, []); if (!items) return <Loading />; return <section className="space-y-4"><div><h1 className="text-2xl font-bold">Workflow Library</h1><p className="text-sm text-slate-500">Reusable, project-ready workflow structures. <Source /></p></div>{items.map(item => <article key={item.id} className="rounded-xl border bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">{item.name}</h2><span className="text-xs text-slate-500">Standard SLA: {item.standardSlaHours}h</span></div><p className="mt-1 text-sm text-slate-500">{item.description}</p><div className="mt-4 grid gap-3 md:grid-cols-3">{item.stages.map((stage, index) => <div key={stage.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{index + 1}. {stage.name}</b><p className="mt-1 text-xs text-slate-500">Gate: {stage.gate} · {stage.slaHours}h</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Skills: {item.requiredSkills.join(', ')} · Playbooks: {item.playbooks.map(p => p.title).join(', ')}</p></article>)}</section>; }

export function KnowledgeHub({ mode = 'knowledge' }) { const [items, setItems] = useState(); useEffect(() => { (mode === 'pilot' ? operationsService.listPilots() : mode === 'outcome' ? operationsService.listOutcomes() : operationsService.listKnowledge()).then(setItems); }, [mode]); if (!items) return <Loading />; const copy = mode === 'pilot' ? ['Workflow pilots', 'Test packages and workflows with customers.'] : mode === 'outcome' ? ['Customer outcomes', 'Connect completion and resolution back to the customer.'] : ['Knowledge Hub & Playbooks', 'Project learning is linked to future workflow gates.']; return <section className="space-y-4"><div><h1 className="text-2xl font-bold">{copy[0]}</h1><p className="text-sm text-slate-500">{copy[1]} <Source /></p></div>{items.map(item => <article key={item.id} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{item.title || item.customer?.name}</h2><p className="mt-1 text-sm text-slate-600">{item.description || `${item.workflow?.name} · ${item.status} · ${item.implementationProgress}% implemented`}</p><p className="mt-3 text-xs text-slate-500">{mode === 'knowledge' ? `${item.type} · ${item.gate} · ${item.status}` : mode === 'outcome' ? `${item.project?.name} · SLA ${item.slaAchieved ? 'achieved' : 'not achieved'} · ${item.resolutionStatus}` : `SLA: ${item.slaResult} · Friction: ${item.friction}`}</p></article>)}</section>; }
